name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        plugin:
          - unittest         
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: asdf-vm/actions/install@v2
      - name: asdf_plugin_test
        run: |
          asdf plugin add helm-${{ matrix.plugin }} https://github.com/vitalis/asdf-helm-plugin
          ASDF_HELM_PLUGIN_DEBUG=1 asdf install helm-${{ matrix.plugin }} latest
          helm ${{ matrix.plugin }} -h